### PR TITLE
Madgwick AHRS

### PR DESCRIPTION
**Pull request by psychogenic**
Have integrated the Madgwick AHRS OSS algorithm and modified the library to (optionally) auto-update the filter on calls to readSensor().

You can see it in action in this short clip: https://youtu.be/ndcm4gHl944

This pull also includes a new example to try out the AHRS functionality.

### CODE REVIEW

**Comment by flybrianfly** [comment]
Cool! Thanks for pulling this, it has been oft requested. Let me try the new features, might be a few days before merging...

**Comment by psychogenic** [comment]
Ok, great.
FYI, I've put up some notes on my experience with the '9250 and using this lib at https://flyingcarsandstuff.com/2018/04/quick-easy-attitude-and-heading-reference-system/

Check it out if curious and, if you do, let me know if you notice any errors/omissions/issues.

Cheers,
P

**Comment by nagyf** [comment]
Any updates on this? :)

**Comment by aster94** [comment]
Hi! I also would love to have all in a single library but also the idea of keeping the roles separated is right (one library for the IMU comunication and one for the AHRS/other filter). Anyway if you want you can try a library i wrote https://github.com/aster94/SensorFusion also note that @flybrianfly wrote a wonderful library https://github.com/bolderflight/uNavAHRS

**Comment by flybrianfly** [comment]
I'm trying to keep this library strictly to reading the sensor and have attitude estimation in a separate library.

**Pull request closed without merging**
