### PR TITLE
Enable switching of the I2C library based on the build board

### PR DESCRIPTION
**Pull request by Doom4535**
Added in preprocessor statements to change the included I2C library and the pointer type for the object.

### CODE REVIEW

**Comment by willie-from-texas** [comment]
Tried this version as I was merging the uNavAHRS_MPU9250 software with a display using the i2c_t3 library. The software used WIRE1 (pins 37 and 38) it "froze" during calibration. On the scope the serial communication stopped when the clock generated 1.05 microsecond pulse (bad timing). Switch to WIRE (pins 19 and 18) and worked but curiously the loop went from 9.8 ms up to 10.1 ms (an increase of about 300 microseconds). Not sure if the problem is with this code or, more probably, the i2c_t3 library. Think I will stay with the wire library since it seems to run faster.

**Comment by Doom4535** [comment]
That is interesting.  Have you been able to test it without the display connected?  It is possible that both the display library and this one are conflicting over the I2C settings?  I'll try to pull this project out after I finish moving.

**Comment by willie-from-texas** [comment]
Forgot to say that I was using a Teensy 3.6. I went back and reconfigured to where I saw the failure. I started by using this library with working code without anything else other than the 9250 connected.
Channel 1 is the interrupt. Channel 2 is SCL, and Channel 3 is SDA. The first scope image is the last good transmission. The second scope image is the failed frame, and the third scope image show the last clock terminating early. I'm not sure where the problem is coming from.
Last good transmission
I2C_t3 Failure
Clock Stop

**Comment by Doom4535** [comment]
What is your hardware setup for the test (as in does this include the I2C screen?)?  Looking back at the request, I didn't update the i2c_t3 call to reference other Wire interfaces (Wire1, Wire2, etc.).  I'd update the wire declaration to use the Wire# that corresponds with the I2C port being used (would explain why the com stops if it tries to switch over to a different hardware port).  Maybe test with the basic example using only the IMU and printing the results via UART to verify first.

Also, how are your external pullups configured?  When you ran with both devices on the same port, did each device have on board pullup resistors?

**Comment by willie-from-texas** [comment]
In my test I only used the 9250 breakout board with two 4.7 K pull-up resistors. Nothing else aside from the USB is connected. The software is driving the serial port on the USB, and is fed into 'Telemetry Viewer'. When I switch to your 9250 library (which uses the i2c_t3 library) the LED blinks once or twice and then it hangs when using the WIRE1 interface. I hooked up my scope and saw the bad clock signal which I published on my last post. On a hunch I reconfigured to the WIRE port and it worked without any issues (although it was about 200 microseconds slower). Unfortunately I have been distracted by other activities and haven't had the time to research it any further. My eventual goal is to interface to the ILI 9488 TFT LED 3.5" display (currently have a 16-bit interface working) with the second I2C port supporting a capacitive touch panel. When I worked on the LED display software I used the i2c_t3 library. I naively assumed I could use the i2c_t3 library directly with the 9250 library. I saw the work that you did as a part of that learning experience and thought I'd try it.
If I can get everything to work with the wire library (and from the small test case I ran it appears the wire library runs a little faster) then I'm good. Hopefully I can find the time to complete that integration test tomorrow.
Thanks for being so responsive. By the way I saw your youtube video where you were driving the 3-d model through a bluetooth interface using quaternions and thought that was pretty slick. I'm currently using quaternions to drive the monkey model in Telemetry Viewer.
Best, 
Willie

**Comment by willie-from-texas** [comment]
Hey Doom,

I got everything I needed to work using the Wire library with no problems. Let me know if you want to continue to debug this problem. I parked a version of my code that reproduces the bug.

Regards,
Willie

**Comment by Doom4535** [comment]
Thank you for the info, I'll try to look at this after I finish moving in the next few weeks.  I may also try to add a way to switch hardware ports to the library declaration.

I think you may have me confused with another person for the YouTube video.  For reference, which video is this?

**Comment by Doom4535** [comment]
@willie-from-texas I just pushed a few changes and included an example for using with a Teensy board ([examples/Basic_I2C_Teensy/MPU9250_I2C_Test.ino](https://github.com/Doom4535/MPU9250/blob/master/examples/Basic_I2C_Teensy/MPU9250_I2C_Test.ino)).  

If you want to modify the settings to use something different from the default I2C settings for that port, you will need to call Wire#.begin(<your_settings>) before you call IMU.begin() so that your custom settings are written (causing the _i2c.begin() call in IMU.begin() to do nothing? seems to ignore the second begin() call so I'll roll with it).

For all the custom settings supported by i2c_t3, checkout: https://github.com/nox771/i2c_t3

@willie-from-texas If you are able to, could you run through and double check the performance differences?  I lack the equipment to inspect this, but was under the impression that the i2c_t3 library was the better performing option (although, the default arduino libraries may have improved to the point where this is no longer relevant).

**Comment by Doom4535** [comment]
Also, if you build this with Platform.io, you may want to add `lib_ldf_mode = chain+` to your `platformio.ini` file, otherwise it will likely try to include both the `Wire` and `i2c_t3` libraries as it won't try to process all the preprocessor define statements.

**Comment by flybrianfly** [comment]
I'd like to keep everything on TwoWire, especially since i2c_t3 does not support the Teensy 4.x line.

**Pull request closed without merging**
